apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-instance
  template:
    metadata:
      labels:
        app: apache-instance
    spec:
      containers:
      - name: apache-instance
        image: httpd:latest
        ports:
        - containerPort: 80
      
