version: '3.8'
services:
  webapp:
    image: surajit1986/phpapp:v2
    container_name: phpapp-instance
    networks:
      - app-network
    ports:
       - "80:80"
  db:
    image: surajit1986/mysql-image:latest
    container_name: mysql-instance
    networks:
      - app-network
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sqlset1010
networks:
  app-network:
    name: "app-network"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  mysql-data: