apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb-deployment
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: mongodb-backend
  template: 
    metadata: 
      labels:
        app: mongodb-backend
    spec: 
      containers:
      - name: mongodb-instance
        image: mongodb-image:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 27017
