apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-instance
  template:
    metadata:
      labels:
        app: ubuntu-instance
    spec:
      containers:
      - name: ubuntu-instance
        image: ubuntu
        command: ["/bin/sleep", "3600"]
      
