apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-deployment
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: mysql-backend
  template: 
    metadata: 
      labels:
        app: mysql-backend
    spec: 
      containers:
      - name: mysql-instance
        image: mysql-examimage:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
